CONNECT TO WAHLSYS;
CREATE TABLE KORBI.BUNDESLAND ( ID BIGINT  NOT NULL  GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1, NO CACHE ) , 
NAME VARCHAR (255)  NOT NULL  , 
CONSTRAINT CC1288606507352 PRIMARY KEY ( ID)  ) ;



CREATE TABLE KORBI.WAHLKREIS ( ID BIGINT  NOT NULL  GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1, NO CACHE ) , 
BUNDESLANDID BIGINT  NOT NULL , 
NAME VARCHAR (255)  , 
CONSTRAINT CC1288606603901 PRIMARY KEY ( ID) , 
CONSTRAINT CC1288606617285 FOREIGN KEY (BUNDESLANDID) REFERENCES KORBI.BUNDESLAND (ID)  ON DELETE NO ACTION ON UPDATE NO ACTION ENFORCED  ENABLE QUERY OPTIMIZATION  ) ;



CREATE TABLE KORBI.WAHLBEZIRK ( ID BIGINT  NOT NULL  GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1, NO CACHE ) , 
WAHLKREISID BIGINT  NOT NULL  , 
CONSTRAINT CC1288606788792 PRIMARY KEY ( ID) , 
CONSTRAINT CC1288606799462 FOREIGN KEY (WAHLKREISID) REFERENCES KORBI.WAHLKREIS (ID)  ON DELETE NO ACTION ON UPDATE NO ACTION ENFORCED  ENABLE QUERY OPTIMIZATION  ) ;



CREATE TABLE KORBI.PARTEI ( ID BIGINT  NOT NULL  GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1, NO CACHE ) , 
NAME VARCHAR (255)  NOT NULL , 
KUERZEL VARCHAR (63)  NOT NULL  , 
CONSTRAINT CC1288606983948 PRIMARY KEY ( ID)  ) ;



CREATE TABLE KORBI.LANDESLISTE ( ID BIGINT  NOT NULL  GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1, NO CACHE ) , 
PARTEIID BIGINT  NOT NULL , 
BUNDESLANDID BIGINT  NOT NULL  , 
CONSTRAINT CC1288607097080 PRIMARY KEY ( ID) , 
CONSTRAINT CC1288607102228 FOREIGN KEY (PARTEIID) REFERENCES KORBI.PARTEI (ID)  ON DELETE NO ACTION ON UPDATE NO ACTION ENFORCED  ENABLE QUERY OPTIMIZATION , CONSTRAINT CC1288607115815 FOREIGN KEY (BUNDESLANDID) REFERENCES KORBI.BUNDESLAND (ID)  ON DELETE NO ACTION ON UPDATE NO ACTION ENFORCED  ENABLE QUERY OPTIMIZATION  ) ;



CREATE TABLE KORBI.DIREKTMANDAT ( ID BIGINT  NOT NULL  GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1, NO CACHE ) , 
PARTEIID BIGINT  NOT NULL , 
WAHLKREISID BIGINT  NOT NULL  , 
CONSTRAINT CC1288607225718 PRIMARY KEY ( ID) , 
CONSTRAINT CC1288607232192 FOREIGN KEY (PARTEIID) REFERENCES KORBI.PARTEI (ID)  ON DELETE NO ACTION ON UPDATE NO ACTION ENFORCED  ENABLE QUERY OPTIMIZATION , CONSTRAINT CC1288607245171 FOREIGN KEY (WAHLKREISID) REFERENCES KORBI.WAHLKREIS (ID)  ON DELETE NO ACTION ON UPDATE NO ACTION ENFORCED  ENABLE QUERY OPTIMIZATION  ) ;



CREATE TABLE KORBI.KANDIDAT ( ID BIGINT  NOT NULL  GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1, NO CACHE ) , 
PARTEIID BIGINT  NOT NULL , 
LANDESLISTEID BIGINT  NOT NULL , 
NAME VARCHAR (255)  NOT NULL , 
VORNAME VARCHAR (255)  NOT NULL , 
BERUF VARCHAR (255) , 
GEBURTSDATUM DATE , 
GEBURTSORT VARCHAR (255) , 
ANSCHRIFT VARCHAR (2047)  , 
CONSTRAINT CC1288607383356 PRIMARY KEY ( ID) , 
CONSTRAINT CC1288607389830 FOREIGN KEY (PARTEIID) REFERENCES KORBI.PARTEI (ID)  ON DELETE NO ACTION ON UPDATE NO ACTION ENFORCED  ENABLE QUERY OPTIMIZATION , CONSTRAINT CC1288607400625 FOREIGN KEY (LANDESLISTEID) REFERENCES KORBI.LANDESLISTE (ID)  ON DELETE NO ACTION ON UPDATE NO ACTION ENFORCED  ENABLE QUERY OPTIMIZATION  ) ;

ALTER TABLE KORBI.KANDIDAT ADD COLUMN LISTENPLATZ INTEGER ;


CREATE TABLE KORBI.STIMME ( ID BIGINT  NOT NULL  GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1, NO CACHE ) , 
KANDIDATID BIGINT , 
PARTEIID BIGINT , 
WAHLBEZIRKID BIGINT  NOT NULL , 
GUELTIG SMALLINT  NOT NULL  WITH DEFAULT 0  , 
CONSTRAINT CC1288610679447 PRIMARY KEY ( ID) , 
CONSTRAINT CC1288610689165 FOREIGN KEY (KANDIDATID) REFERENCES KORBI.KANDIDAT (ID)  ON DELETE NO ACTION ON UPDATE NO ACTION ENFORCED  ENABLE QUERY OPTIMIZATION , 
CONSTRAINT CC1288610700714 FOREIGN KEY (PARTEIID) REFERENCES KORBI.PARTEI (ID)  ON DELETE NO ACTION ON UPDATE NO ACTION ENFORCED  ENABLE QUERY OPTIMIZATION , 
CONSTRAINT CC1288610713433 FOREIGN KEY (WAHLBEZIRKID) REFERENCES KORBI.WAHLBEZIRK (ID)  ON DELETE NO ACTION ON UPDATE NO ACTION ENFORCED  ENABLE QUERY OPTIMIZATION  ) ;


CREATE TABLE KORBI.WAHLERGEBNIS1 ( ID BIGINT  NOT NULL  GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1, NO CACHE ) , 
KANDIDATID BIGINT  NOT NULL , 
WAHLBEZIRKID BIGINT  NOT NULL , 
JAHR INTEGER  NOT NULL  , 
CONSTRAINT CC1288610976900 PRIMARY KEY ( ID) , 
CONSTRAINT CC1288610983160 FOREIGN KEY (KANDIDATID) REFERENCES KORBI.KANDIDAT (ID)  ON DELETE NO ACTION ON UPDATE NO ACTION ENFORCED  ENABLE QUERY OPTIMIZATION , 
CONSTRAINT CC1288610994045 FOREIGN KEY (WAHLBEZIRKID) REFERENCES KORBI.WAHLBEZIRK (ID)  ON DELETE NO ACTION ON UPDATE NO ACTION ENFORCED  ENABLE QUERY OPTIMIZATION  ) ;
COMMENT ON TABLE KORBI.WAHLERGEBNIS1 IS 'Wahlergebnis 1. Stimme';


CREATE TABLE KORBI.WAHLERGEBNIS2 ( ID BIGINT  NOT NULL  GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1, NO CACHE ) , 
PARTEIID BIGINT  NOT NULL , 
WAHLBEZIRKID BIGINT  NOT NULL , 
JAHR INTEGER  NOT NULL  , 
CONSTRAINT CC1288610976900 PRIMARY KEY ( ID) , 
CONSTRAINT CC1288610983160 FOREIGN KEY (PARTEIID) REFERENCES KORBI.PARTEI (ID)  ON DELETE NO ACTION ON UPDATE NO ACTION ENFORCED  ENABLE QUERY OPTIMIZATION , 
CONSTRAINT CC1288610994045 FOREIGN KEY (WAHLBEZIRKID) REFERENCES KORBI.WAHLBEZIRK (ID)  ON DELETE NO ACTION ON UPDATE NO ACTION ENFORCED  ENABLE QUERY OPTIMIZATION  ) ;
COMMENT ON TABLE KORBI.WAHLERGEBNIS2 IS 'Wahlergebnis 2. Stimme';


CONNECT RESET;
